name:                mars-rover
version:             0.1.0.0
author: Stefano
# maintainer: futtetennista@pm.me
extra-source-files:
- README.md
- stack.yaml
dependencies:
- base == 4.14.3.0
- bytestring == 0.10.12.0
ghc-options:
- -Wall
- -Werror
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
# workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)
- -optP-Wno-nonportable-include-path
tested-with: GHC == 8.10.7
library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - GeneralizedNewtypeDeriving
    - BlockArguments
    - LambdaCase
  dependencies:
    - attoparsec == 0.13.2.5

executables:
  mars-rover:
    main:                Main.hs
    source-dirs:         app
    ghc-options: []
      # - -threaded
      # - -rtsopts
      # - -with-rtsopts=-N
    dependencies:
      - mars-rover

tests:
  mars-rover-test:
    default-extensions:
      - OverloadedStrings
      - GeneralizedNewtypeDeriving
      - BlockArguments
      - LambdaCase
      - TypeApplications
    main: Main.hs
    source-dirs: test/
    dependencies:
    - QuickCheck == 2.14.2
    - mars-rover
    - tasty == 1.4.2.1
    - tasty-hunit == 0.10.0.3
    - tasty-quickcheck == 0.10.2
    - tasty-expected-failure == 0.12.3
