name:                mars-rover
version:             0.1.0.0
author: Stefano
# maintainer: futtetennista@pm.me
extra-source-files:
- README.md
- stack.yaml
dependencies:
- base == 4.14.3.0
ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
# workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)
- -optP-Wno-nonportable-include-path
library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - GeneralizedNewtypeDeriving
    - BlockArguments
    - LambdaCase
  dependencies:
    # - array
    # - bytestring
    - attoparsec # 0.13.2.5
    # - parser-combinators
    # - transformers

executables:
  application:
    main:                Main.hs
    source-dirs:         app
    ghc-options: []
      # - -threaded
      # - -rtsopts
      # - -with-rtsopts=-N
    dependencies:
      - mars-rover

tests:
  mars-rover-test:
    default-extensions:
      - OverloadedStrings
      - GeneralizedNewtypeDeriving
      - BlockArguments
      - LambdaCase
      - TypeApplications
    main: Main.hs
    source-dirs: test/
    dependencies:
    - attoparsec # 0.13.2.5
    - bytestring # 0.10.12.0
    - QuickCheck # 2.14.2
    - mars-rover
    - tasty # 1.4.2
    - tasty-hunit # 0.10.0.3
    - tasty-quickcheck # 0.10.1.2

